docker_image: "ubuntu:15.10"
env:
  FOO: foo
  BAR: bar
packages:
- ruby
dependencies:
- gem install bundler
test:
- echo "Tests!"
build_in_parallel:
- sub_project: 'sub_project_a/.bt.yml'
  env:
    PARENT_FOO: $FOO
    PARENT_BAR: 'simple'
- service: github
  organization: pcorliss
  name: buildtree_tester_2
  branch: master
  env:
    PARENT_FOO: $FOO
    PARENT_BAR: 'simple'
build_on_success:
- sub_project: 'sub_project_b/.bt.yml'
  env:
    PARENT_FOO: $FOO
    PARENT_BAR: 'simple'
- service: github
  organization: pcorliss
  name: buildtree_tester_2
  branch: master
